# Generated by Django 5.0.14 on 2025-05-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_price_product_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
